version: '3.3'
services:
  neo4j:
    image: neo4j:latest
    environment:
      - NEO4J_AUTH=none
    volumes:
      - ./neo4j/conf:/conf
      - ./neo4j/data:/data
      - ./neo4j/import:/import
      - ./neo4j/logs:/logs
      - ./neo4j/plugins:/plugins
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
  web:
    build: ./backend
    command: python app.py
    ports:
      - '8000:5000'
    depends_on:
      - neo4j
